server:
  port: ${server.port}
  servlet:
    session:
      cookie:
        domain: localhost
    context-path: /api #默认访问前缀


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lotus_match?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: "0721"
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: lotus_match

  session:
    timeout: 43200
    store-type: redis
  redis:
    port: 6379
    host: localhost
    database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.lotus.pojo

knife4j:
  enable: true

server_profile:
  ip: 127.0.0.1
  port: 8080
