server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lotus_match?characterEncoding=utf8&useSSL=false
    username: root
    password: "0721"
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: lotus_match
  session:
    timeout: 43200
    store-type: redis


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.lotus.pojo

knife4j:
  enable: true